// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz1-RFCecZxQQVguGQE-fAXiR9LXpq9iM',
    appId: '1:896521942010:web:5aa2c57c4241b7ad6dea43',
    messagingSenderId: '896521942010',
    projectId: 'task-app-7d137',
    authDomain: 'task-app-7d137.firebaseapp.com',
    storageBucket: 'task-app-7d137.appspot.com',
    measurementId: 'G-4J62T4886K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAW_P1xNWD5y1wgqzGoJPdkfJxkF28qRw',
    appId: '1:896521942010:android:48d317c6f9a82e7f6dea43',
    messagingSenderId: '896521942010',
    projectId: 'task-app-7d137',
    storageBucket: 'task-app-7d137.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCjpiu3BjJapdHa6tZ6g3da-bPicujwJg',
    appId: '1:896521942010:ios:a0d4dfe58bdc7a216dea43',
    messagingSenderId: '896521942010',
    projectId: 'task-app-7d137',
    storageBucket: 'task-app-7d137.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCjpiu3BjJapdHa6tZ6g3da-bPicujwJg',
    appId: '1:896521942010:ios:a0d4dfe58bdc7a216dea43',
    messagingSenderId: '896521942010',
    projectId: 'task-app-7d137',
    storageBucket: 'task-app-7d137.appspot.com',
    iosBundleId: 'com.example.taskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDz1-RFCecZxQQVguGQE-fAXiR9LXpq9iM',
    appId: '1:896521942010:web:b5c51f8e399e9e046dea43',
    messagingSenderId: '896521942010',
    projectId: 'task-app-7d137',
    authDomain: 'task-app-7d137.firebaseapp.com',
    storageBucket: 'task-app-7d137.appspot.com',
    measurementId: 'G-VENKNSHXKM',
  );
}
